# Generated by Django 5.0.1 on 2024-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post_pic.jpg', null=True, upload_to='post_pics'),
        ),
    ]
