# Generated by Django 5.0.1 on 2024-02-20 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_react_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='react',
            unique_together={('user', 'post')},
        ),
    ]
