# Generated by Django 5.0.1 on 2024-02-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_react_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='react',
            unique_together=set(),
        ),
    ]
