# Generated by Django 5.0.1 on 2024-03-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_lastestreact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastestReact',
        ),
    ]
