# Generated by Django 5.0.1 on 2024-03-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_curr_place_profile_curr_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='curr_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Living place'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='curr_work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current work'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Dating', 'Dating'), ('Married', 'Married'), ('Private', 'Private')], max_length=10, null=True),
        ),
    ]
